#!/bin/bash

. /etc/wifi/variscite-wifi.conf
. /etc/wifi/variscite-wifi-common.sh

WIFI_SLEEP=1
WIFI_SLEEP_5G=5

wifi_setup()
{
	if [ ! -f /sys/class/gpio/gpio${WIFI_EN_GPIO}/direction ]; then
		echo ${WIFI_EN_GPIO} > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio${WIFI_EN_GPIO}/direction
	fi

	if [ ! -f /sys/class/gpio/gpio${BT_EN_GPIO}/direction ]; then
		echo ${BT_EN_GPIO} > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio${BT_EN_GPIO}/direction
	fi

	if som_is_dart_6ul_5g; then
		if [ ! -f /sys/class/gpio/gpio${WIFI_PWR_GPIO}/direction ]; then
			echo ${WIFI_PWR_GPIO} > /sys/class/gpio/export
			echo out > /sys/class/gpio/gpio${WIFI_PWR_GPIO}/direction
		fi

		WIFI_SLEEP=${WIFI_SLEEP_5G}
	fi
}

wifi_is_up()
{
	for i in `seq 1 8`; do
		[ -d /sys/class/net/wlan0 ] && return 0
		sleep 1
	done

	return 1
}

#################################################
#              Execution starts here            #
#################################################

# Exit if WIFI is disabled on DART-6UL
if grep -q MX6UL /sys/devices/soc0/soc_id && \
   ! grep -iq WiFi /sys/devices/soc0/machine; then
   exit 0
fi

# Run initial setup sequence
wifi_setup

for i in `seq 1 3`; do

	# Up WIFI
	wifi_up

	# Check that WIFI interface is up
	if wifi_is_up; then
		echo "WIFI startup success"
		exit 0
	fi

	# Down WIFI
	wifi_down

	# Wait enough time for discharge
	sleep ${WIFI_SLEEP}
done

echo "WIFI startup failed"

exit 1
