#!/bin/sh -e
#
# Activate Bluetooth for Variscite boards
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.

# Load board-specific configuration settings
. /etc/bluetooth/variscite-bt.conf
. /etc/bluetooth/variscite-bt-common.sh

###########################
#  Execution starts here  #
###########################
case $1 in
start)
	bt_start
	;;
stop)
	bt_stop
	;;
esac

exit 0
