#!/bin/bash

# rootfs packages machine learning stage

# apply debconfig options
debconf-set-selections /debconf.set
rm -f /debconf.set

function protected_install()
{
	local _name=${1}
	local repeated_cnt=5;
	local RET_CODE=1;

	echo Installing ${_name}
	for (( c=0; c<${repeated_cnt}; c++ ))
	do
		apt install -y ${_name} && {
			RET_CODE=0;
			break;
		};

		echo
		echo "##########################"
		echo "## Fix missing packages ##"
		echo "##########################"
		echo

		sleep 2;

		apt --fix-broken install -y && {
			RET_CODE=0;
			break;
		};
	done

	return ${RET_CODE}
}

# update packages and install base
apt-get update || apt-get upgrade

# machine learning packages
protected_install imx-nn

# sudo kill rootfs-stage-ml
rm -f rootfs-stage-ml